export const UPDATE_SEARCHING_TITLE = 'UPDATE_SEARCHING_TITLE'
export const GET_SEARCHING_MOVIES = 'GET_SEARCHING_MOVIES'
export const GET_MOVIE_GENRES = 'GET_MOVIE_GENRES'

export const UPDATE_PAGE = 'UPDATE_PAGE'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
